
# you need to set the root_path to handy_voting
root_path: './'

# setup details about user study
title: 'user study for text-to-image generation'
guideline: [
  'choose the image you think is the best matched one to the prompt',
  'choose the image you think has the best quality',
]

# you need to specify the models
models: [
    {
        name: 'a',
        type: 'reference',
    },
    {
        name: 'b',
        type: 'target',
    },
    {
        name: 'c',
        type: 'baseline',
    },
]


APP_SETTINGS:
    # DO NOT change the following
    SQLALCHEMY_DATABASE_URI: 'sqlite:///${root_path}/../imgvoter.db'
    SECRET_KEY: 'y8nh0ng-U6q97dp'

    # [can be changed] number of models pick from baselines for comparison
    NUM_MODELS: 1

    DATA_DIR: 'static/data/image'
    DATA_TYPE: 'image'
